### ISSUE TITLE
What does width mean in the appendBitmap function do specifically?

### ISSUE THREAD

**Issue by Dwikavindra** [star-micronics/StarPRNT-SDK-Android-Java#10]
## Description
Hi I'm quite confused on the appendBitmap in the ICommandBuilder function. It seems to have multiple overloads where it has width specified to it, and where it doesn't. The documentation only says the width is "Bitmap width after conversion. (Units : Dots)". So does that mean that if my bitmap width is larger than my printer paper receipt width it's going to try to convert it to the specified width I put in? If so how would I calculate that if I have multiple printers?. For the `appendBitmap(Bitmap bitmap, boolean diffusion);
`
if I use that one instead, would it automatically adjust my bitmap so that it the width fits with any printer that supported by STAR? Im having a hard time finding the Pixel Width on Star's page any help with that,please? @gare-bear @Lozrus @bandit-ibayashi 

Current Printer: M-Pop

**Comment by gare-bear** [comment]
@Dwikavindra

> So does that mean that if my bitmap width is larger than my printer paper receipt width it's going to try to convert it to the specified width I put in?

Yes. its as simple as that. if the width of the image is larger than the printable area, then specifying width as a parameter will attempt to scale it down. You should also specify if you want both width and height scaled to preserve the aspect ratio. Otherwise, the image may be skewed. 

if you have 

> so how would I calculate that if I have multiple printers?.

If you're targeting two different printers, or printers with different print widths you'll need to define a command builder object for each printer. 

> Im having a hard time finding the Pixel Width on Star's page 
> Current Printer: mPOP

the mPOPs printable area is 384px at its default setting.

**Comment by Dwikavindra** [comment]
> If you're targeting two different printers, or printers with different print widths you'll need to define a command builder object for each printer

Would this mean that just by setting the right command builder, I don't need to set the width of printing from the appendBitmap command as that would be handled automatically ? @gare-bear

**Comment by Dwikavindra** [comment]
Is there any way to get the printer width in dots? Or do I need to create a different function that maps the different dots for each printer?  Can't seem to find it on the docs , what I'm intending is to be able to scale down an image in accordance to the printer width in dot and then print it. @gare-bear

**Comment by Tatsuki-Yamamoto2731** [comment]
@Dwikavindra I'm sorry for the late response. We added a general indication of the number of dots to be specified for each paper width in the Wiki. Please refer to [this page](https://github.com/star-micronics/StarPRNT-SDK-Android-Java/wiki/Number-of-dots-for-each-paper-width).
