### ISSUE TITLE
How to easily print in reverse direction?

### ISSUE THREAD

**Issue by tomasvalek** [star-micronics/StarPRNT-SDK-Android-Java#12]
## Description
**Printer:** SK1-311SF4-Q-SP, firmware 2.2, interface USB

**Android SDK**:
"com.starmicronics:stario:2.11.0
"com.starmicronics:starioextension:1.15.1

**Problem**:
How to print in reverse direction? See image: https://imageupload.io/ZE9dt2KL5l3giEC

I cannot found it in tutorial: www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/android_java/en/getting_start.html#

Thank you

**Comment by bandit-ibayashi** [comment]
@tomasvalek Apologies for my late reply.
We are afraid to say that "SK1-311SF4-Q-SP" does not have a capability to print in reverse direction by using its own font.

As an alternative approach, there will be the method to generate receipt data using Bitmap images in the Android device, rotate it 180 degrees in the device and send the rotated Lester receipt data to the printer.

The following is a sample code for generating a Bitmap from text.
https://github.com/star-micronics/StarPRNT-SDK-Android-Java/blob/379a501be430c73d0df2583ac9733c6b7b9e83e5/SDK/app/src/main/java/com/starmicronics/starprntsdk/localizereceipts/ILocalizeReceipts.java#L221

Thank you.
