### ISSUE TITLE
How to set Bitmap in the Center 

### ISSUE THREAD

**Issue by SidSpPlus** [star-micronics/StarPRNT-SDK-Android-Java#14]
builder.appendBitmapWithAlignment(createBitmapFromText(model.title, textSize, 384, typeface), true, ICommandBuilder.AlignmentPosition.Center);

**Comment by bandit-ibayashi** [comment]
@SidSpPlus Could you please provide enough information for us to investigate this Issue using the template?
Also if you are using TSP100 or TSP100III, this method will always be left-justified.

**Comment by SidSpPlus** [comment]
I am using sm230i printer

**Comment by bandit-ibayashi** [comment]
Please confirm your SM-S230i setting if its setting is "EMU = StarPRNT" by the following way.
https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/android_java/en/getting_start.html#gettingstart-printer
![image](https://github.com/star-micronics/StarPRNT-SDK-Android-Java/assets/60959945/9a2bb7f9-63e0-4215-af8d-34b957c3544b)

If "EMU=ESC/POS", this method will always align to the left.

**Comment by bandit-ibayashi** [comment]
This Issue is closed as there has been no movement for over 6 months. If you continue to have issues, please let us know.
