### ISSUE TITLE
Is there any way to increase font size without making bold or dark?

### ISSUE THREAD

**Issue by SidSpPlus** [star-micronics/StarPRNT-SDK-Android-Java#15]
## Description
A clear and concise description.

## Your device where the bug occurs 
 - Device: 
    *e.g. iPhone 13*
 - OS:
    *e.g. iOS 15.0*
 - Browser: 
    *e.g. Safari*
 - Version
    *e.g. 22*

## Your printer
- Model Names:
    *e.g. mC-Print3*
- Firmware Version:
    *e.g. 3.5*
- Interface:
    *e.g. Ethernet*

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.

## Additional context
Any other context about your topic.

**Comment by SidSpPlus** [comment]
Any update or suggestion here?

**Comment by bandit-ibayashi** [comment]
@SidSpPlus Could you please provide enough information for us to investigate this Issue using the template?
Thank you in advance.

**Comment by bandit-ibayashi** [comment]
I think this is a same issue https://github.com/star-micronics/StarXpand-SDK-Android/issues/21#issuecomment-1987900088
So I would like to close this.
