### ISSUE TITLE
TSP100 increasing font size and making font bold

### ISSUE THREAD

**Issue by sharpwitz** [star-micronics/StarPRNT-SDK-Android-Java#4]
We are having trouble increasing font size and making the font bold before converting the text to image for the TSP100 printer.

If it is possible - could you also please provide a code snippet or reference to the sample, which will generate a Bitmap for TSP-100 printer with two lines of text on it:

    First line with BIG bold font 
    Second line with normal font

![sample3](https://user-images.githubusercontent.com/538437/110152245-7b851480-7daf-11eb-8e76-84a53989281e.jpg)

**Comment by gare-bear** [comment]
@sharpwitz sorry for the delayed response. I can get you an example but in the interim, take a look at our code in ILocalizeReceipts. We set the typeface and font size directly on the Paint object and then draw that on your Rect object.

https://github.com/star-micronics/StarPRNT-SDK-Android-Java/blob/23a400e8292721fbff772e8b6fc73dc0db40e08b/SDK/app/src/main/java/com/starmicronics/starprntsdk/localizereceipts/ILocalizeReceipts.java#L221-L243

appendMultiple magnifies text drawn using native printer fonts. In this case, since you're using the TSP100 this isn't applicable since it's a Raster-only printer and has no native printer fonts. It will completely ignore this method.

**Comment by sharpwitz** [comment]
could you give an example to make a receipt like Ryan O receipt
including top logo image
![tsp100-9](https://user-images.githubusercontent.com/538437/112783291-00fd8c80-901d-11eb-8e21-eee3a0b243d2.jpg)

**Comment by gare-bear** [comment]
Here's an example of a method that takes some input; e.g. an address, and returns a Bitmap. The text drawn to the Bitmap is center aligned, bold and using a 30pt monospaced font.
```
static public Bitmap createBitmapFromAddress(String address, int textSize, int printWidth, Typeface typeface) {
{
        Paint paint = new Paint();
        Bitmap bitmap;
        Canvas canvas;

        address = "65 Clyde Road\n" + // addresses usually
                "Somerset NJ 08873\n" +  // span several lines
                "908-123-4567"; // phone numbers often centered too

        paint.setTextSize(30); // set font size
        paint.setTypeface(Typeface.create(Typeface.MONOSPACE, Typeface.BOLD)); // set font type and weight

        paint.getTextBounds(printText, 0, printText.length(), new Rect());

        TextPaint textPaint = new TextPaint(paint);
        textPaint.setTextAlign(Paint.Align.CENTER); // center align the drawn text
        android.text.StaticLayout staticLayout = new StaticLayout(address, textPaint, 576, Layout.Alignment.ALIGN_NORMAL, 1, 0, false);

        // Create bitmap
        bitmap = Bitmap.createBitmap(staticLayout.getWidth(), staticLayout.getHeight(), Bitmap.Config.ARGB_8888);

        // Create canvas
        canvas = new Canvas(bitmap);
        canvas.drawColor(Color.WHITE);
        canvas.translate(canvas.getWidth() / 2, 0);
        staticLayout.draw(canvas);

        return bitmap;
    }
```
This isn't the full receipt but it does demonstrates how to make the font bigger and how to bold.

Logos can be printed using [appendBitmap](https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/android_java/en/api_starioext_i_command_builder.html#appendbitmap) or drawn using the approach shown above.

**Comment by sharpwitz** [comment]
Could you give an actual full receipt example which would show some font
bold and some font regular and alignment changes where some text centered
but other text left align.  Maybe even a line divider before the Total.
