### ISSUE TITLE
Can I print text as italic?

### ISSUE THREAD

**Issue by vuduongopn** [star-micronics/StarPRNT-SDK-Android-Java#6]
Hello developer,

I am using your SDK in my application for printers. But I don't know how to print text as italic. I don't know if the library supports this? Please let me know.

Thank you so much.

**Comment by gare-bear** [comment]
@vuduongopn Star printers cannot natively print in italic. They do support some basic formatting options like inverted text (white text on black background), bold, and underline, but unfortunately not italic. 

That being said, you can create your receipt as an image and use an italic font when drawing your text. Then add the resulting Bitmap to an ICommandBuilder object using the [appendBitmap](https://www.star-m.jp/products/s_print/sdk/starprnt_sdk/manual/android_java/en/api_starioext_i_command_builder.html#appendbitmap) method.
