### ISSUE TITLE
Androidx Support

### ISSUE THREAD

**Issue by darktiny** [star-micronics/StarPRNT-SDK-Android-Java#7]
I don't understand why `starioextension` needs `appcompat`, but it did. Please migrate from `android support` to `androidx`. Since it's the only third party lib that still need android support libs in my project. And I have to enable `Jetifier` just because of this.
```
\--- com.starmicronics:starioextension:1.15.0
     +--- com.android.support:appcompat-v7:21.0.0
```

**Comment by bandit-ibayashi** [comment]
@darktiny Sorry for my late response and thank you for your report.
Your report will be corrected in the next update.

Until the update, add `android.enableJetifier=true` to the `gradle.properties` file as a temporary workaround.

Thank you for your patience and understanding.

**Comment by bandit-ibayashi** [comment]
@darktiny We have fixed this issue where apps configured to use AndroidX could not be built if Jetifier was not used.
We would appreciate your confirmation that this update will resolve the issue.

Thank you for your patience!

**Comment by darktiny** [comment]
@bandit-ibayashi fixed
