### ISSUE TITLE
Connect to printer using custom apps

### ISSUE THREAD

**Issue by anditestmobile** [star-micronics/StarPRNT-SDK-Android-Java#8]
Hi, i have the printer Mc Print3. how can i using the printer for my android custom app?do you have the easy way to do? 
how to connect to the printer using my custom app and to do print receipt?

Thank you

**Comment by gare-bear** [comment]
@anditestmobile This SDK (the StarPRNT SDK) is a printer communications for Android systems. Using our library, you can integrate printing to your mC-Print3. 

If this is your first time integrating a Star printer, you might want to start by checking out the [README](https://github.com/star-micronics/StarPRNT-SDK-Android-Java/blob/master/README.md) and the [documentation](https://star-m.jp/products/s_print/sdk/starprnt_sdk/manual/android_java/en/index.html). 

You can also contact your a local [support](https://starmicronics.com/contact-us/) team in your region  if you prefer 1-1 support.

**Comment by anditestmobile** [comment]
Hi @gare-bear thank you for your response,
Yes this is my first time integrating a star printer and i already checking the documentation. i still confuse how to print using my custom app.
because i just want to auto print using the printer when i click button print receipt. 
is there any code how to connect the printer to the app and print the receipt?
Thank you

**Comment by bandit-ibayashi** [comment]
If anyone would like to develop a new Android application with our printers, we recommend that you use the [StarXpand SDK](https://github.com/star-micronics/StarXpand-SDK-Android).

StarXpand SDK is the successor to StarPRNT SDK with further improvements. Sample code is provided for each basic function, such as searching for printers, printing, and getting status, which will be especially useful if you want to implement a function that prints a receipt when a button is pressed, as in this Issue.

We appreciate your understanding.

**Comment by bandit-ibayashi** [comment]
This issue will be closed once as there has been no movement for some time. If you continue to have problems, please open this issue or create a new one.

Thank you for your understanding!
