### ISSUE TITLE
[BUG] Impossible to pair STAR mPop printer

### ISSUE THREAD

**Issue by edenbergel** [star-micronics/StarPRNT-SDK-Android-Java#9]
## Description
Impossible to connect STAR mPop printer after updating my Android tablet

## Your device where the bug occurs 
 - Device: 
 *samsung s7+
 samsung Galaxy tab S7+ 
samsung galaxy tab s7 FE 
Galaxy Tab S7 FE 5G
 samsung galaxy tab S6 light*

 - OS: tested on 
    *Android 11 - 12*

## Your printer
- Model Names:
    *STAR mPop*
- Firmware Version: tested on 
    * 2 - 4*

## To Reproduce
1. Go to Bluetooth
2. Connect your device to mPop printer
3. Impossible to connect

## Expected behavior
Being able to connect to the printer

## Screenshots
https://user-images.githubusercontent.com/43988978/195642305-3917c213-a370-4bb7-a1c6-316869d113ab.mp4

## Additional context
I tried to connect to two Galaxy Tab A  (Android 11, same versions for everything)  : 
- serial number : SM-T510 ( works fine )
- serial number : SM-T515 ( doesn't work )
I don't know if it has anything to do with it but it might be something to look into

**Comment by bandit-ibayashi** [comment]
@edenbergel Sorry we have not been able to answer the Issue you posted.
And this is an occurrence at the time of pairing, so we do not consider it to be a relevant phenomenon for this repository.

We would ask you to contact our POINT OF SALE SOLUTIONS team in your area by clicking on the link below.
https://starmicronics.com/global
